default_platform(:android)

platform :android do

  desc "🧪 Run unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "🚀 Deploy DEVELOPMENT flavor to Internal Testing"
  lane :development_internal do
    gradle(task: "clean")

    android_set_version_code(
      gradle_file: "app/build.gradle",
      version_code: android_get_version_code(
        gradle_file: "app/build.gradle"
      ).to_i + 1
    )

    gradle(
      task: "bundle",
      flavor: "development",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'internal',
      json_key: "fastlane/keys/reactnativeignitekit-465baf38544b.json",
      package_name: "com.shivshankartiwari.reactnativeignitekit",
      skip_upload_apk: true,
      skip_upload_screenshots: false
    )
  end

  desc "🧪 Deploy STAGING flavor to Open Testing (Beta)"
  lane :staging_beta do
    gradle(task: "clean")

    android_set_version_code(
      gradle_file: "app/build.gradle",
      version_code: android_get_version_code(
        gradle_file: "app/build.gradle"
      ).to_i + 1
    )

    gradle(
      task: "bundle",
      flavor: "staging",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'beta',
      json_key: "fastlane/keys/reactnativeignitekit-465baf38544b.json",
      package_name: "com.shivshankartiwari.reactnativeignitekit",
      skip_upload_apk: true,
      skip_upload_screenshots: false
    )
  end

  desc "🏁 Deploy PRODUCTION flavor to Production"
  lane :production_release do
    gradle(task: "clean")

    android_set_version_code(
      gradle_file: "app/build.gradle",
      version_code: android_get_version_code(
        gradle_file: "app/build.gradle"
      ).to_i + 1
    )

    gradle(
      task: "assemble",
      flavor: "production",
      build_type: "Release"
    )

    gradle(
      task: "bundle",
      flavor: "production",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'production',
      json_key: "fastlane/keys/reactnativeignitekit-465baf38544b.json",
      package_name: "com.shivshankartiwari.reactnativeignitekit",
      skip_upload_apk: true,
      skip_upload_screenshots: false
    )
  end

end
